create table attempt (id bigint generated by default as identity, attempt_count bigint, attempt_status bigint, end_date_time binary(255), start_date_time binary(255), test_id bigint, user_id bigint, primary key (id))
create table card (id bigint generated by default as identity, answer varchar(255), question varchar(255), primary key (id))
create table post_card (topic_id bigint not null, card_id bigint not null)
create table test (topic_id bigint not null, primary key (topic_id))
create table test_card (id bigint generated by default as identity, is_correct boolean, test_level bigint, attempt_id bigint, card_id bigint, primary key (id))
create table topic (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, first_name varchar(255), last_name varchar(255), primary key (id))
alter table attempt add constraint FKndl37di25vpn387aepg7qqyoc foreign key (test_id) references test
alter table attempt add constraint FK4oy0ej0j4den4q5hrogi4oyj0 foreign key (user_id) references user
alter table post_card add constraint FK1ryt81qw1va78w0qx54bqfb5a foreign key (card_id) references card
alter table post_card add constraint FKottchvqaiaof2oiv8n508adpr foreign key (topic_id) references topic
alter table test add constraint FK28pij4g1cy47c8q7a4aouj6v6 foreign key (topic_id) references topic
alter table test_card add constraint FK4y36ftjf0eonq9ju6mifr1wwt foreign key (attempt_id) references attempt
alter table test_card add constraint FKrlv8w1rmwosoq4l76mqjlfktm foreign key (card_id) references card
