create table attempt (id bigint generated by default as identity, attempt_count bigint, attempt_status bigint, end_date_time binary(255), start_date_time binary(255), exam_id bigint, user_id bigint, primary key (id))
create table card (id bigint generated by default as identity, answer varchar(255), question varchar(255), primary key (id))
create table exam (topic_id bigint not null, primary key (topic_id))
create table exam_card (id bigint generated by default as identity, is_correct boolean, test_level bigint, attempt_id bigint, card_id bigint, primary key (id))
create table post_card (topic_id bigint not null, card_id bigint not null)
create table topic (id bigint generated by default as identity, name varchar(255), primary key (id))
create table user (id bigint generated by default as identity, first_name varchar(255), last_name varchar(255), primary key (id))
alter table attempt add constraint FKiqtj38gvtx6b5862e5kec3eil foreign key (exam_id) references exam
alter table attempt add constraint FK4oy0ej0j4den4q5hrogi4oyj0 foreign key (user_id) references user
alter table exam add constraint FKkcuey063e9q6my2rqbw3uo4ec foreign key (topic_id) references topic
alter table exam_card add constraint FKgt32x0pc6bsehyaj7cnwhu7nd foreign key (attempt_id) references attempt
alter table exam_card add constraint FKktlwbd6fwo3lpxsrqcrvojhla foreign key (card_id) references card
alter table post_card add constraint FK1ryt81qw1va78w0qx54bqfb5a foreign key (card_id) references card
alter table post_card add constraint FKottchvqaiaof2oiv8n508adpr foreign key (topic_id) references topic
